# sudo required for rabbitmq service
sudo: required

language: java

jdk:
  - oraclejdk8

before_install:
  - ./mvnw -f tools/dnorm/pom.xml -DskipTests compile

cache:
  directories:
  - $HOME/.m2
  - linnaeus-data

services:
  - rabbitmq